spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ec2-3-137-217-127.us-east-2.compute.amazonaws.com:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:mjgguser}
    password: ${SPRING_DATASOURCE_PASSWORD:mjggpass}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
